apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
  namespace: messager
type: Opaque
stringData:
  POSTGRES_USER: "CHANGEME"
  POSTGRES_PASSWORD: "CHANGEME"
  POSTGRES_DB: "CHANGEME"
  DB_DSN_USER: "host=postgres user=CHANGEME password=CHANGEME dbname=CHANGEME_users sslmode=disable"
  DB_DSN_MSG: "host=postgres user=CHANGEME password=CHANGEME dbname=CHANGEME_messages sslmode=disable"
